def_event_types([
    f1(a, time),
    f2(a, time),
    f3(a, time),
    f4(a, time),
    f5(a, time),
    f6(a, time),
    f7(a, time),
    f8(a, time),
    f9(a, time),
    f10(a, time),
    f11(a, time),
    f12(a, time),
    f13(a, time),
    f14(a, time),
    f15(a, time),
    f16(a, time),
    f17(a, time),
    f18(a, time),
    f19(a, time),
    f20(a, time)
 ]).
