=== Example and tests

Bartosz Zieliński <bartosz.zielinski@fis.uni.lodz.pl>

Apart from the app code itself, `PatternExplorer` folder also contains some files related to examples and tests. All the files below aside from 
`example_data.pl` are inside `tests` subfolder.

==== example_data.pl

This file contains definition of bus traffic control event schema and example patterns and tests. The format is described in section <<_input_file_syntax>>.

==== auto_simple.pl

This is an alternative implementation of search automaton used in timing tests (section <<_evaluation>>)  which represents single skipped events by constrained variables.

==== timed_test.pl

This file contains prolog program which performs tests which times our tool under varying parameters (we use alternative automaton implementation).
Unfortunately, modifying the test parameters is not very user-friendly.

==== analyze_test.py

This is a Python3 script which processes csv file with raw results produced by `timed_test.pl` file and generates plots used in the paper (see section <<_evaluation>>). The script assumes that the csv file is named `test.csv` and produces files named `nsols.png` and `cpu.png`. To change that one has to modify the source file. 

==== test.csv

This is the file generated by `timed_test.pl` on author's computer. We included it in the repository for reproducibility.